### ISSUE TITLE
[Ch1 SubA][Pacmom] 보완 작업

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/GameOver#290]
# [Ch1 SubA][Pacmom] 보완 작업

### 1차 목표

- [x] 먼지 오프닝 대사 말소리 삽입 (임시)
- [x] 팩맘&먼지 충돌시 랜덤하게 코인 떨구기
- [x] 오프닝 대사 자동 넘김 (2초)
- [x] 설정창 프리팹 적용 (설정창 켜면 timeScale 0)
- [x] Movement 테스트 코드 오류 수정 *=> 하단 '문제'에 기술*
- [x] 라플리가 팩맘 코인 뺏었을 때 텀을 두고 코인수 1씩 올리기 *=> 코루틴으로 구현, 효과음 있으면 좋을 듯*
- [x] 사운드 볼륨 수정된 버전 적용
- [x] 먼지 말소리 음절 단위로 적용
- [x] 먼지 인게임 말풍선&글자 사이즈 증가 *=> 1.15배 키움*
- [x] 방문 끼임 현상 *=> 하단 '문제'에 기술*
- [x] 먼지 오프닝&엔딩 대사 수정 *=> [이슈 코멘트](https://github.com/GG-Studio-990001/GameOver/issues/299#issuecomment-1933796640) 참고*

### 2차 목표

- [x] 말풍선&방문 스프라이트 교체
- [x] 라플리&먼지 충돌시 먼지 대사 (ex. 길 막지마!) *=> [이슈 코멘트](https://github.com/GG-Studio-990001/GameOver/issues/299#issuecomment-1937714035) 참고*
- [x] 같은 코너를 여러 바퀴 도는 것 수정 *=> 하단 '문제'에 기술*
- [x] 오프닝 말풍선 애니메이션 적용
*=> 오프닝 말풍선은 기존 다른 애니메이션들과 달리 spriteRenderer가 아닌 Image임. Slice 기능을 써야하기 때문. 그래서 새로 스크립트를 만들어줬는데 다른 애니메이션들과 발동 시간?이 다른 느낌...*
- [x] 청소기 시간에 주변 코인들도 획득
*=> 기존보다 큰 사이즈의 Circle Collider를 가지는 오브젝트를 팩맘의 자식으로 둠. 또한 "Vacuum"이라는 Tag를 걸어서 코인은 충돌, 먼지는 충돌 안되게 설정*
- [x] 청소기 코인 흡수 애니메이션
- [x] 청소 중 또 청소기 획득 시 먼지 대사 변화 *=> [이슈 코멘트](https://github.com/GG-Studio-990001/GameOver/issues/299#issuecomment-1938452599) 참고*

*코드리뷰, 테스트 코드, 리팩터링도...*
*다음 마일스톤 때 대형 리팩터링 ㄱㄱ => 이후 코드리뷰*

### 리소스 받고 작업

- 사운드 볼륨 수정 (기화)
   - 요청 ✅
   - 확인 ✅
- 먼지 오프닝 말소리 음절 단위로 (기화)
   - 요청 ✅
   - 확인 ✅
- 오프닝 말풍선 애니메이션 (세화)
   - 요청 ✅
   - 확인 ✅

---

### Movement 테스트 코드 오류

**배경**
![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/afdca8bb-81de-48d2-baef-87f4314365b8)
*원래 함수*
해당 함수, 그리고 같은 로직을 쓰는 팩맘 무브먼트 함수에서 에러 확인

처음에는 Run All을 50번 정도 눌렀는데 오류를 확인하지 못함
그러다가 함수 하나씩만 돌려보니까 바로 오류 발생

로그 찍어보면 -0.16과 0(에러) 중에 하나가 찍힘

`yield return new WaitForFixedUpdate();`  이 코드를 통해 FixedUpdate를 기다려줌

이 코드를 두 줄 써줬더니 -0.16과 0.32 중 하나가 찍힘
에러는 나지 않음

**생각**
결론적으로 FixedUpdate가 하나 씹히거나, 기다리는 시간이 너무 짧아서 씹히거나??
아무튼 움직일 수 있는 시간이 너무 짧아서 간헐적으로 이런 오류가 생긴거라고 생각함

![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/bcb1ada0-3521-4350-ba6c-1ee7454e5d30)
정안님의 Movement 코드는 에러가 나지 않는데, 
정안님은 Move 함수를 직접적으로 호출하고 나는 FixedUpdate에 Move가 호출되길 기다려서 차이가 난다고 생각

**해결**
FixedUpdate를 하나 기다려주는 것보다만 기다리는 시간이 길면 오류가 발생하지 않음
WaitForFixedUpdate를 두 번 호출해도 되고, WaitForSeconds를 호출해도 됨
`yield return new WaitForSeconds(0.1f);` 로 바꿈
(0.64 이동하므로 FixedUpdate가 4번 정도 호출되는 듯..)

### 방문 끼임 현상

**배경**

![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/ec16132e-f783-4165-ba82-39131cd438aa)

먼지들이 방문을 나설 때 끼이는 현상 발견
아주 간헐적으로 발생되어서 관측하기 쉽지 않음.
(아직도 제대로 오류 발생 과정을 확인하지 못함)

**생각**

라플리의 움직임이 먼지를 아래로 밀고,
밀린 먼지는 해당 위치에 발판이 없어서 움직이지 못하는 것으로 추측됨.

**해결**
(1)
처음에는 방문이 있는 자리에도 발판을 설치함
발판은 방문이 없을 때 활성화되며 밟으면 무조건 위로만 이동 가능
하지만 같은 오류가 계속 나타남

(2)
방문 쪽에 먼지가 특정 시간 이상 머물러있으면 (낑겨있으면)
먼지를 옮겨주는 코드를 생각함
코드가 너무 깔끔하지 않을 것 같음

(3) => 현재
먼지들이 방문을 나가는 코루틴을 수정하기로 함.
원래는 방문 밖(A)으로만 내보내는 건데,
끼임을 방지하기 위해 좀 더 바깥(B, C)까지 내보내기로 함
![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/16bcd257-a73b-4c40-9042-43389ed66e7e)

QA 후 (3)으로도 해결이 되지 않는다면 다른 방법을 구색해 볼 예정...

### 팩맘의 코너 무한 루프

**배경**

![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/8afb0705-12a7-4138-b7df-2ca71224629d)

이런 코너에서 팩맘이 여러바퀴 계속 돌 때 멍청해 보일 수 있음

*확률 억까이기도 하지만 맵을 조금 복잡하게 만든게 주 원인...*

**해결**

처음에는 코너쪽의 발판에 몇번 밟았는지 카운트를 할까 하다가
단순하게 가기로 함

원래 갈림길에 있는 발판은 그 위치에서 갈 수 있는 방향들 중에 하나를 골라서 가는 방식 (갈 수 있는 방향이 3가지라면 각각 동일한 확률, 대신 바로 반대 방향으로 꺾는 것은 지양)

![스크린샷 2024-02-11 232838](https://github.com/GG-Studio-990001/GameOver/assets/80298207/f7945341-3f3e-4631-8500-5c3f08c22817)

해결을 위해 오른쪽 또는 왼쪽으로 갈 확률이 높은 특수 발판을 설치해줌

![스크린샷 2024-02-11 232931](https://github.com/GG-Studio-990001/GameOver/assets/80298207/015d0e2d-2873-4ccf-899c-8de3988d8f52)

초록 발판은 오른쪽으로 갈 확률 60%
파란 발판은 왼쪽으로 갈 확률 60%

결론적으로 팩맘과 먼지들은 코너에 갇히지 않을 확률이 올라감

---

<details><summary> 메모 </summary>

**연결 작업**
~*정안님과 비정기 회의 후 작업 예정 => 2/2금 회의*~

- 탑다운 씬과 연결
   => 추후 (현재 기획 대규모 수정 중)
- 2회차 시 먼지유령 대사 변화
   => 추후 ??? (회의 때 말 못했다..)
- 설정창, 키 통일
   => 할 일로 이동

**기타**
- 게임팩에 들어가고 나가는 연출 필요
   => 정안님이 하기로
- 대사 출력 에셋
   => 퀄리티업 단계에서 메인씬과 같이 적용

**아트**
방문, 게임팩 필요
(게임팩은 현재 Old TV 쉐이더니까 오래된 컴퓨터 같은 것도 좋을 듯)
![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/bd4baed9-75a6-4032-b316-0fc703e5c826)

**!!**
설정창 UI esc로 끄고 켜면 괜찮은데
esc로 켜고 x 버튼으로 끄면 timeScale 1로 안돌아옴

</details>

**Comment by wooyn730** [comment]
@fkdl0048 

생각 다 적었습니다! 대사만 적으려다 쓰는 김에 다 썼더니 길어졌네요
이슈랑 코멘트에 있는 부분만 해결하면 팩맘은 정말 끝날 것 같습니다

---

## 먼지유령 말풍선&대사에 대한 생각

(1)
오프닝 대사로 게임 룰을 이해시키는 게 1순위여야 된다고 생각함

(2)
현재 먼지유령들이 기업의 사원, 라플리가 신입인 설정인데
팩맘은 '맘', '청소기', '먼지' 같은 고유의 컨셉이 있으므로
직장인보다는 악동 같은 말투도 괜찮을 것 같음

(3)
현재 인게임 내 작은 말풍선으로 나오는 대사는
랜덤 대사(퇴사하고 싶은 직장인 느낌), 청소기 대사(도망가) 등임
랜덤 대사의 출현 빈도를 낮추고
팩맘을 쫓거나 쫓길 때, 팩맘을 잡거나 잡혔을 때 등의
특별한 상황에서의 대사를 추가해도 좋을 듯

(4)
먼지유령과 팩맘과 조금 떨어진 상태에서
플레이어가 코인을 먹는 것에 집중하면
팩맘이 먼지유령에게 잡혀 위치가 초기화되었을 때
어리둥절한 경우가 종종 있음
이 부분은 3번의 팩맘을 잡았을 때 대사를 추가하면 나아질 것 같음

## 팩맘 AI에 대한 생각

너무 바보같이 보이지 않도록 조금씩 고쳐오긴 함
가장 최근 주요 변동 사항은
(1) 갈림길에서 랜덤 방향이 아닌 코인이 존재하는 방향으로 가는 것
(2) 이미 잡혀 방에 갇힌 먼지유령&라플리를 쫓으려 하지 않는 것
이 두 가지임

현재 팩맘의 조금 바보같은(?) 부분은
(1) 가끔 같은 곳을 몇바퀴 도는 것
![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/0d9a2963-c7a9-468a-abd5-dbdf078a407c)
(2) 벽 뒤에 있는 벽을 쫓으려 벽을 멤도는 것
![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/aab78f3a-5ce0-4d76-8f3e-319c80ff22b6)
이 정도인데 서브 시스템에서 이 정도 지능이면 괜찮다고 생각함

## 할 일 목록에 남아있는 것

사실 초기 기획에 따르면 해야할 것이 세 가지 더 있음

(1) 먼지유령 시간차 나오기 (더 긴 간격으로)
(2) 먼지유령, 라플리 잡혔을 때 걸어서 방 들어가기
(3) 필드에 남은 코인 라플리가 흡수할 때 빨아들이는 애니메이션

*(1), (2)번은 팩맨과 유사성을 더하기 위한 부분,
(3)번은 라플리만의 특이함(?)을 보여주기 위한 부분*

우선순위가 낮고, 조금 귀찮고, 필요성이 느껴지지 않아서 작업을 보류중이었음...

정안님 생각도 들어보고
없어도 괜찮을 것 같으면 작업 목록에서 빼는 방향으로 가고싶음
(물론 필요하다고 하면 작업해야겠쬬)

**Comment by fkdl0048** [comment]
> 오프닝 대사로 게임 룰을 이해시키는 게 1순위여야 된다고 생각함

회의 때 말씀드린 대로 동의하고 내용은 수정해보셔도 되고 따로 손대고 싶지 않으시면 전달 드리겠습니다

> 현재 먼지유령들이 기업의 사원, 라플리가 신입인 설정인데 팩맘은 '맘', '청소기', '먼지' 같은 고유의 컨셉이 있으므로 직장인보다는 악동 같은 말투도 괜찮을 것 같음

같은 말이라 작성을 원하시는지 아니면 전달받는게 편하신지 말씀해주세요.

> 현재 인게임 내 작은 말풍선으로 나오는 대사는 랜덤 대사(퇴사하고 싶은 직장인 느낌), 청소기 대사(도망가) 등임 랜덤 대사의 출현 빈도를 낮추고 팩맘을 쫓거나 쫓길 때, 팩맘을 잡거나 잡혔을 때 등의 특별한 상황에서의 대사를 추가해도 좋을 듯

같은 답변

> 먼지유령과 팩맘과 조금 떨어진 상태에서 플레이어가 코인을 먹는 것에 집중하면 팩맘이 먼지유령에게 잡혀 위치가 초기화되었을 때 어리둥절한 경우가 종종 있음 이 부분은 3번의 팩맘을 잡았을 때 대사를 추가하면 나아질 것 같음

말씀해주신 부분들을 적용해보고 회의 때 보면 좋을 것 같아요

## 팩맘 AI에 대한 생각, 할 일 목록에 남아있는 것

회의 때 계속해서 완성도를 언급하는 이유에서 이 문제에 대한 답변이 될 것 같습니다.

지금도 충분히 잘 구현된 상태라고 생각하지만, 이 정도면 된 것 같다는 아닌 것 같습니다.

우연님께서 팩맘 AI의 수정이 불가능하거나 너무 어려운 것이 아니라면 당연하게 1, 2의 문제는 해결하는 게 맞고, 서브 시스템이라고 해서 이 정도 지능을 넘기는 것은 아니라고 생각됩니다.

만약 현재 코드에서 수정하기 어렵거나 문제가 있다면 말씀 해주세요.

>  우선순위가 낮고, 조금 귀찮고, 필요성이 느껴지지 않아서 작업을 보류중이었음...

마찬가지로 아직 제가 기획을 정리하지 않아서 내용을 제대로 파악하지 못했지만, 시스템에서 필요한 부분은 당연하게 추가하는 게 맞고 필요 없다면 빼는 게 맞지만, 귀찮아서 추가 못하는 부분은 없었으면 합니다..!

이 부분은 제가 더 정리해보고 필요한 부분에 대해서 같이 이야기 해보면 좋을 것 같습니다.

만약 구현의 어려움이 있다면 솔직하게 말씀해주시고 해결방법을 같이 찾는게 좋을 것 같아요

**Comment by wooyn730** [comment]
> 먼지유령 말풍선&대사에 대한 생각

그러면 상관 없다는 걸로 이해하고 제가 이슈 따로 생성해서 먼지유령 대사 수정&추가해보겠습니다.

> 팩맘 AI에 대한 생각

우선, *서브 시스템에서 이 정도 지능이면 괜찮다고 생각함*이라는 것은 서브 시스템이니 대충하고 넘기겠다는 의미는 아니었습니다.

팩맘의 지능이나 사고방식과 관련된 것은 기획서에 포함되지 않았습니다.
쫓는다, 쫓긴다, 코인 쪽으로 이동한다는 설명만 있고 자세한 수치는 기입되지 않았으므로 임의로 '적당히' 설정했습니다.

'적당히'는 제 기준으로 게임을 플레이하기 적합한 정도였습니다.
팩맘이 가끔 같은 곳을 돌거나 벽 뒤를 왔다갔다 거리는 것은
게임 플레이에 해가 되지 않고, 오히려 그 시간동안 플레이어는 득을 볼 수 있는 요소로도 사용할 수 있다고 생각했습니다.

기획 상에서 밸런싱 문제로 고쳐야 한다거나,
플레이어가 너무 답답함을 느꼈다거나 하면 물론 고쳐야하겠지만
단순히 AI를 개선하는 것이 게임의 완성도를 높인다고는 생각하지 않습니다..

> 할 일 목록에 남아있는 것

(1), (2)번 같은 경우에도 기획서에 명시되어 있는 부분은 아닙니다.
다만 기획자분과 소통하던 중에 팩맨은 이러하니 팩맘도 이렇게 구현해도 좋을 것 같다라고 들었던 것입니다.

(3)번도 지금 코인 획득 방식도 괜찮다고 이야기하신 적이 있었습니다.

[이 이슈](https://github.com/GG-Studio-990001/GameOver/issues/270)에도 동호님의 코멘트가 있는데, 저는 팩맘 기획을 이야기할 때 '확실히 구현해달라는 요청'보다는 '~해도 괜찮겠다는 의견'을 많이 받았다고 느꼈습니다.

'귀찮다'라는 것은 어감이 나쁘긴 하지만..
저는 추가할 필요성을 느끼지 못해서 의견을 확실하게 여쭤본 것이었습니다.
(만약 팩맨에서 라플리를 추가하고 스킨만 갈아낀 것처럼 보이는게 기획 의도였다면 (1), (2)번을 당연히 반영해야하지만 적당히 오마주한 게임이라면 없으면 없는대로 차이가 될 것이라고 생각)

---

사실 이번 팩맘 기획서가 디테일한 편은 아닙니다.
그래서 제 주관도 이미 꽤 들어가 있기도 합니다.

그리고 모든 서브 시스템이 완벽할 필요도 없다고 생각합니다.
모든 게임 개발자가 게임을 완벽하게 만들지는 않으니까요.
그렇게 만들어진 수많은 게임들이 모이는 곳이기도 하고요.
(하지만 재미는 있긴 해야겠죠..)

아무튼 제가 보류하고 있던 부분들은 단순히 귀찮음만이 이유가 아닌 걸 알아주셨으면 좋겠고 ㅠ
그 부분들이 꼭 필요한 게 맞는지 한 번 더 체크 부탁드립니다.
(고집 부릴 생각은 없습니댜..)

**Comment by fkdl0048** [comment]
말씀하신 내용 잘 이해하였고, 개발 과정에서 기획서 내용이 완벽할 수 없다고 생각합니다.

그래서 시스템적인 부분을 제외하고는 주관적인 부분이 계속 반영되고 있고, 그래야 한다고 생각합니다.

그럼에도 디렉터와 같이 결정을 내리거나 방향성을 잡아주는 역할이 필요한데, 동호님이 빠지게 되면서 QA나 기획서 내용을 검증하고 추가할 부분이 부족했던 것 같네요

위에서 말씀드린 대로 현재 구현된 내용에서 수정되어야 할 부분, 추가되어야 할 부분을 정리해서 같이 이야기 해보는 게 가장 좋은 방법인 것 같습니다.

일단 플밍 비정기 회의 전까지 내용 파악해서 참여하도록 하겠습니다!
